###
POST http://localhost:5000/api/users HTTP/1.1
Content-Type: application/json


{
  "nombre": "deleter",
  "apellido": "ghcghcghcghcghi",
  "posicion": "Delantero",
  "imagenUrl": "https://i.ibb.co/XJBfFd3/messsi.png"
}

###
GET http://localhost:5000/api/users HTTP/1.1

###
GET http://localhost:5000/api/users/638127d0021ef63d475df993 HTTP/1.1

###
DELETE http://localhost:5000/api/users/63814eaa506aa139b5384f70 HTTP/1.1

###
PUT http://localhost:5000/api/users/639b9873559f9f70b6099903 HTTP/1.1
Content-Type: application/json

{
  "nombre": "admin",
  "apellido": "zxxvvzv",
  "posicion": "Delantero",
  "imagenUrl": "https://i.ibb.co/XJBfFd3/messsi.png"
}
